package exercisies.make;

import exercisies.model.Exercisies;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

public class MakeExercisies {
    private List<Exercisies> exercisiesListBr = Arrays.asList(
            new Exercisies("01_EstruturaSequencial", Arrays.asList(
                    "1 - Faça um Programa que mostre a mensagem \"Alo mundo\" na tela.\nExercícios encontrados em wiki.python.org.br",
                    "2 - Faça um Programa que peça um número e então mostre a mensagem O número informado foi [número].\nExercícios encontrados em wiki.python.org.br",
                    "3 - Faça um Programa que peça dois números e imprima a soma.\nExercícios encontrados em wiki.python.org.br",
                    "4 - Faça um Programa que peça as 4 notas bimestrais e mostre a média.\nExercícios encontrados em wiki.python.org.br",
                    "5 - Faça um Programa que converta metros para centímetros.\nExercícios encontrados em wiki.python.org.br",
                    "6 - Faça um Programa que peça o raio de um círculo, calcule e mostre sua área.\nExercícios encontrados em wiki.python.org.br",
                    "7 - Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.\nExercícios encontrados em wiki.python.org.br",
                    "8 - Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.\nExercícios encontrados em wiki.python.org.br",
                    "9 - Faça um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius.\nC = 5 * ((F-32) / 9).\nExercícios encontrados em wiki.python.org.br",
                    "10 - Faça um Programa que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit.\nExercícios encontrados em wiki.python.org.br",
                    "11 - Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre:\no produto do dobro do primeiro com metade do segundo .\na soma do triplo do primeiro com o terceiro.\no terceiro elevado ao cubo.\nExercícios encontrados em wiki.python.org.br",
                    "12 - Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58\nExercícios encontrados em wiki.python.org.br",
                    "13 - Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:\nPara homens: (72.7*h) - 58\nPara mulheres: (62.1*h) - 44.7 \nExercícios encontrados em wiki.python.org.br",
                    "14 - João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas.\nExercícios encontrados em wiki.python.org.br",
                    "15 - Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:\nsalário bruto.\nquanto pagou ao INSS.\nquanto pagou ao sindicato.\no salário líquido.\ncalcule os descontos e o salário líquido, conforme a tabela abaixo:\n\n+ Salário Bruto : R$\n- IR (11%) : R$\n- INSS (8%) : R$\n- Sindicato ( 5%) : R$\n= Salário Liquido : R$\n\nObs.: Salário Bruto - Descontos = Salário Líquido.\nExercícios encontrados em wiki.python.org.br",
                    "16 - Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total.\nExercícios encontrados em wiki.python.org.br",
                    "17 - Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00 ou em galões de 3,6 litros, que custam R$ 25,00.\n\nInforme ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações:\ncomprar apenas latas de 18 litros;\ncomprar apenas galões de 3,6 litros;\nmisturar latas e galões, de forma que o desperdício de tinta seja menor. Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias.\nExercícios encontrados em wiki.python.org.br",
                    "18 - Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos)\nExercícios encontrados em wiki.python.org.br."
            )),
            new Exercisies("02_EstruturaDeDecisao", Arrays.asList(
                    "01 - Faça um Programa que peça dois números e imprima o maior deles.\nExercícios encontrados em wiki.python.org.br",
                    "02 - Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.\nExercícios encontrados em wiki.python.org.br",
                    "03 - Faça um Programa que verifique se uma letra digitada é \"F\" ou \"M\". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.\nExercícios encontrados em wiki.python.org.br",
                    "04 - Faça um Programa que verifique se uma letra digitada é vogal ou consoante.\nExercícios encontrados em wiki.python.org.br",
                    "05 - Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:\n\nA mensagem \"Aprovado\", se a média alcançada for maior ou igual a sete;\nA mensagem \"Reprovado\", se a média for menor do que sete;\nA mensagem \"Aprovado com Distinção\", se a média for igual a dez. \nExercícios encontrados em wiki.python.org.br",
                    "06 - Faça um Programa que leia três números e mostre o maior deles.\nExercícios encontrados em wiki.python.org.br",
                    "07 - Faça um Programa que leia três números e mostre o maior e o menor deles.\nExercícios encontrados em wiki.python.org.br",
                    "08 - Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.\nExercícios encontrados em wiki.python.org.br",
                    "09 - Faça um Programa que leia três números e mostre-os em ordem decrescente.\nExercícios encontrados em wiki.python.org.br",
                    "10 - Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem \"Bom Dia!\", \"Boa Tarde!\" ou \"Boa Noite!\" ou \"Valor Inválido!\", conforme o caso.\nExercícios encontrados em wiki.python.org.br",
                    "11 - As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes.\n\nFaça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:\nsalários até R$ 280,00 (incluindo) : aumento de 20%\nsalários entre R$ 280,00 e R$ 700,00 : aumento de 15%\nsalários entre R$ 700,00 e R$ 1500,00 : aumento de 10%\nsalários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:\no salário antes do reajuste;\no percentual de aumento aplicado;\no valor do aumento;\no novo salário, após o aumento. \nExercícios encontrados em wiki.python.org.br",
                    "12 - Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, que depende do salário bruto (conforme tabela abaixo) e 3% para o Sindicato e que o FGTS corresponde a 11% do Salário Bruto, mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os descontos. O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.\n\nDesconto do IR:\nSalário Bruto até 900 (inclusive) - isento\nSalário Bruto até 1500 (inclusive) - desconto de 5%\nSalário Bruto até 2500 (inclusive) - desconto de 10%\nSalário Bruto acima de 2500 - desconto de 20% Imprima na tela as informações, dispostas conforme o exemplo abaixo. No exemplo o valor da hora é 5 e a quantidade de hora é 220.\n\nSalário Bruto: (5 * 220)        : R$ 1100,00\n(-) IR (5%)                     : R$   55,00\n(-) INSS ( 10%)                 : R$  110,00\nFGTS (11%)                      : R$  121,00\nTotal de descontos              : R$  165,00\nSalário Liquido                 : R$  935,00\nExercícios encontrados em wiki.python.org.br",
                    "13 - Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.\nExercícios encontrados em wiki.python.org.br",
                    "14 - Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos obedece à tabela abaixo:\n\nMédia de Aproveitamento  Conceito\nEntre 9.0 e 10.0        A\nEntre 7.5 e 9.0         B\nEntre 6.0 e 7.5         C\nEntre 4.0 e 6.0         D\nEntre 4.0 e zero        E\n\nO algoritmo deve mostrar na tela as notas, a média, o conceito correspondente e a mensagem “APROVADO” se o conceito for A, B ou C ou “REPROVADO” se o conceito for D ou E. \nExercícios encontrados em wiki.python.org.br",
                    "15 - Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.\n\nDicas:\nTrês lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;\nTriângulo Equilátero: três lados iguais;\nTriângulo Isósceles: quaisquer dois lados iguais;\nTriângulo Escaleno: três lados diferentes; \nExercícios encontrados em wiki.python.org.br",
                    "16 - Faça um programa que calcule as raízes de uma equação do segundo grau, na forma ax2 + bx + c. O programa deverá pedir os valores de a, b e c e fazer as consistências, informando ao usuário nas seguintes situações:\n\nSe o usuário informar o valor de A igual a zero, a equação não é do segundo grau e o programa não deve fazer pedir os demais valores, sendo encerrado;\nSe o delta calculado for negativo, a equação não possui raizes reais. Informe ao usuário e encerre o programa;\nSe o delta calculado for igual a zero a equação possui apenas uma raiz real; informe-a ao usuário;\nSe o delta for positivo, a equação possui duas raiz reais; informe-as ao usuário; \nExercícios encontrados em wiki.python.org.br",
                    "17 - Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não bissexto.\nExercícios encontrados em wiki.python.org.br",
                    "18 - Faça um Programa que peça uma data no formato dd/mm/aaaa e determine se a mesma é uma data válida.\nExercícios encontrados em wiki.python.org.br",
                    "19 - Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.\n\nObservando os termos no plural a colocação do \"e\", da vírgula entre outros. Exemplo:\n326 = 3 centenas, 2 dezenas e 6 unidades\n12 = 1 dezena e 2 unidades Testar com: 326, 300, 100, 320, 310,305, 301, 101, 311, 111, 25, 20, 10, 21, 11, 1, 7 e 16 \nExercícios encontrados em wiki.python.org.br",
                    "20 - Faça um Programa para leitura de três notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e presentar:\n\nA mensagem \"Aprovado\", se a média for maior ou igual a 7, com a respectiva média alcançada;\nA mensagem \"Reprovado\", se a média for menor do que 7, com a respectiva média alcançada;\nA mensagem \"Aprovado com Distinção\", se a média for igual a 10. \nExercícios encontrados em wiki.python.org.br",
                    "21 - Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.\n\nExemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;\nExemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1. \nExercícios encontrados em wiki.python.org.br",
                    "22 - Faça um Programa que peça um número inteiro e determine se ele é par ou impar. Dica: utilize o operador módulo (resto da divisão).\nExercícios encontrados em wiki.python.org.br",
                    "23 - Faça um Programa que peça um número e informe se o número é inteiro ou decimal. Dica: utilize uma função de arredondamento.\nExercícios encontrados em wiki.python.org.br",
                    "24 - Faça um Programa que leia 2 números e em seguida pergunte ao usuário qual operação ele deseja realizar. O resultado da operação deve ser acompanhado de uma frase que diga se o número é:\n\npar ou ímpar;\npositivo ou negativo;\ninteiro ou decimal. \nExercícios encontrados em wiki.python.org.br",
                    "25 - Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:\n\n\"Telefonou para a vítima?\"\n\"Esteve no local do crime?\"\n\"Mora perto da vítima?\"\n\"Devia para a vítima?\"\n\"Já trabalhou com a vítima?\" O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como \"Suspeita\", entre 3 e 4 como \"Cúmplice\" e 5 como \"Assassino\". Caso contrário, ele será classificado como \"Inocente\".\nExercícios encontrados em wiki.python.org.br",
                    "26 - Um posto está vendendo combustíveis com a seguinte tabela de descontos:\n\nÁlcool:\naté 20 litros, desconto de 3% por litro\nacima de 20 litros, desconto de 5% por litro\nGasolina:\naté 20 litros, desconto de 4% por litro\nacima de 20 litros, desconto de 6% por litro Escreva um algoritmo que leia o número de litros vendidos, o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente sabendo-se que o preço do litro da gasolina é R$ 2,50 o preço do litro do álcool é R$ 1,90. \nExercícios encontrados em wiki.python.org.br",
                    "27 - Uma fruteira está vendendo frutas com a seguinte tabela de preços:\n\n                      Até 5 Kg           Acima de 5 Kg\nMorango         R$ 2,50 por Kg          R$ 2,20 por Kg\nMaçã            R$ 1,80 por Kg          R$ 1,50 por Kg\nSe o cliente comprar mais de 8 Kg em frutas ou o valor total da compra ultrapassar R$ 25,00, receberá ainda um desconto de 10% sobre este total. Escreva um algoritmo para ler a quantidade (em Kg) de morangos e a quantidade (em Kg) de maças adquiridas e escreva o valor a ser pago pelo cliente. \nExercícios encontrados em wiki.python.org.br",
                    "28 - O Hipermercado Tabajara está com uma promoção de carnes que é imperdível. Confira:\n\n                      Até 5 Kg           Acima de 5 Kg\nFile Duplo      R$ 4,90 por Kg          R$ 5,80 por Kg\nAlcatra         R$ 5,90 por Kg          R$ 6,80 por Kg\nPicanha         R$ 6,90 por Kg          R$ 7,80 por Kg\n\nPara atender a todos os clientes, cada cliente poderá levar apenas um dos tipos de carne da promoção, porém não há limites para a quantidade de carne por cliente. Se compra for feita no cartão Tabajara o cliente receberá ainda um desconto de 5% sobre o total da compra. Escreva um programa que peça o tipo e a quantidade de carne comprada pelo usuário e gere um cupom fiscal, contendo as informações da compra: tipo e quantidade de carne, preço total, tipo de pagamento, valor do desconto e valor a pagar.\nExercícios encontrados em wiki.python.org.br"
            )),
            new Exercisies("03_EstruturaDeRepeticao", Arrays.asList(
                    "01 - Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.\nExercícios encontrados em wiki.python.org.br",
                    "02 - Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.\nExercícios encontrados em wiki.python.org.br",
                    "03 - Faça um programa que leia e valide as seguintes informações:\n\n    Nome: maior que 3 caracteres;\n    Idade: entre 0 e 150;\n    Salário: maior que zero;\n    Sexo: \"f\" ou \"m\";\n    Estado Civil: \"s\", \"c\", \"v\", \"d\";\nExercícios encontrados em wiki.python.org.br",
                    "04 - Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento.\nExercícios encontrados em wiki.python.org.br",
                    "05 - Altere o programa anterior permitindo ao usuário informar as populações e as taxas de crescimento iniciais. Valide a entrada e permita repetir a operação.\nExercícios encontrados em wiki.python.org.br",
                    "06 - Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.\nExercícios encontrados em wiki.python.org.br",
                    "07 - Faça um programa que leia 5 números e informe o maior número.\nExercícios encontrados em wiki.python.org.br",
                    "08 - Faça um programa que leia 5 números e informe a soma e a média dos números.\nExercícios encontrados em wiki.python.org.br",
                    "09 - Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.\nExercícios encontrados em wiki.python.org.br",
                    "10 - Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.\nExercícios encontrados em wiki.python.org.br",
                    "11 - Altere o programa anterior para mostrar no final a soma dos números.\nExercícios encontrados em wiki.python.org.br",
                    "12 - Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:\n\n    Tabuada de 5:\n    5 X 1 = 5\n    5 X 2 = 10\n    ...\n    5 X 10 = 50\nExercícios encontrados em wiki.python.org.br",
                    "13 - Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem.\nExercícios encontrados em wiki.python.org.br",
                    "14 - Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.\nExercícios encontrados em wiki.python.org.br",
                    "15 - A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo.\nExercícios encontrados em wiki.python.org.br",
                    "16 - A série de Fibonacci é formada pela seqüência 0,1,1,2,3,5,8,13,21,34,55,... Faça um programa que gere a série até que o valor seja maior que 500.\nExercícios encontrados em wiki.python.org.br",
                    "17 - Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120\nExercícios encontrados em wiki.python.org.br",
                    "18 - Faça um programa que, dado um conjunto de N números, determine o menor valor, o maior valor e a soma dos valores.\nExercícios encontrados em wiki.python.org.br",
                    "19 - Altere o programa anterior para que ele aceite apenas números entre 0 e 1000.\nExercícios encontrados em wiki.python.org.br",
                    "20 - Altere o programa de cálculo do fatorial, permitindo ao usuário calcular o fatorial várias vezes e limitando o fatorial a números inteiros positivos e menores que 16. \nExercícios encontrados em wiki.python.org.br",
                    "21 - Faça um programa que peça um número inteiro e determine se ele é ou não um número primo. Um número primo é aquele que é divisível somente por ele mesmo e por 1.\nExercícios encontrados em wiki.python.org.br",
                    "22 - Altere o programa de cálculo dos números primos, informando, caso o número não seja primo, por quais número ele é divisível.\nExercícios encontrados em wiki.python.org.br",
                    "23 - Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário. O programa deverá mostrar também o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados.\nExercícios encontrados em wiki.python.org.br",
                    "24 - Faça um programa que calcule o mostre a média aritmética de N notas.\nExercícios encontrados em wiki.python.org.br",
                    "25 - Faça um programa que peça para n pessoas a sua idade, ao final o programa devera verificar se a média de idade da turma varia entre 0 e 25,26 e 60 e maior que 60; e então, dizer se a turma é jovem, adulta ou idosa, conforme a média calculada.\nExercícios encontrados em wiki.python.org.br",
                    "26 - Numa eleição existem três candidatos. Faça um programa que peça o número total de eleitores. Peça para cada eleitor votar e ao final mostrar o número de votos de cada candidato.\nExercícios encontrados em wiki.python.org.br",
                    "27 - Faça um programa que calcule o número médio de alunos por turma. Para isto, peça a quantidade de turmas e a quantidade de alunos para cada turma. As turmas não podem ter mais de 40 alunos.\nExercícios encontrados em wiki.python.org.br",
                    "28 - Faça um programa que calcule o valor total investido por um colecionador em sua coleção de CDs e o valor médio gasto em cada um deles. O usuário deverá informar a quantidade de CDs e o valor para em cada um.\nExercícios encontrados em wiki.python.org.br",
                    "29 - O Sr. Manoel Joaquim possui uma grande loja de artigos de R$ 1,99, com cerca de 10 caixas. Para agilizar o cálculo de quanto cada cliente deve pagar ele desenvolveu um tabela que contém o número de itens que o cliente comprou e ao lado o valor da conta. Desta forma a atendente do caixa precisa apenas contar quantos itens o cliente está levando e olhar na tabela de preços. Você foi contratado para desenvolver o programa que monta esta tabela de preços, que conterá os preços de 1 até 50 produtos, conforme o exemplo abaixo:\n\n    Lojas Quase Dois - Tabela de preços\n    1 - R$ 1.99\n    2 - R$ 3.98\n    ...\n    50 - R$ 99.50\n\nExercícios encontrados em wiki.python.org.br",
                    "30 - O Sr. Manoel Joaquim acaba de adquirir uma panificadora e pretende implantar a metodologia da tabelinha, que já é um sucesso na sua loja de 1,99. Você foi contratado para desenvolver o programa que monta a tabela de preços de pães, de 1 até 50 pães, a partir do preço do pão informado pelo usuário, conforme o exemplo abaixo:\n\n    Preço do pão: R$ 0.18\n    Panificadora Pão de Ontem - Tabela de preços\n    1 - R$ 0.18\n    2 - R$ 0.36\n    ...\n    50 - R$ 9.00\n\nExercícios encontrados em wiki.python.org.br",
                    "31 - O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar. O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final da compra. O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra. A saída deve ser conforme o exemplo abaixo:\n\n    Lojas Tabajara \n    Produto 1: R$ 2.20\n    Produto 2: R$ 5.80\n    Produto 3: R$ 0\n    Total: R$ 9.00\n    Dinheiro: R$ 20.00\n    Troco: R$ 11.00\n    ...\nExercícios encontrados em wiki.python.org.br",
                    "32 - Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120. A saída deve ser conforme o exemplo abaixo:\n\n    Fatorial de: 5\n    5! =  5 . 4 . 3 . 2 . 1 = 120\nExercícios encontrados em wiki.python.org.br",
                    "33 - O Departamento Estadual de Meteorologia lhe contratou para desenvolver um programa que leia as um conjunto indeterminado de temperaturas, e informe ao final a menor e a maior temperaturas informadas, bem como a média das temperaturas.\nExercícios encontrados em wiki.python.org.br",
                    "34 - Os números primos possuem várias aplicações dentro da Computação, por exemplo na Criptografia. Um número primo é aquele que é divisível apenas por um e por ele mesmo. Faça um programa que peça um número inteiro e determine se ele é ou não um número primo.\nExercícios encontrados em wiki.python.org.br",
                    "35 - Encontrar números primos é uma tarefa difícil. Faça um programa que gera uma lista dos números primos existentes entre 1 e um número inteiro informado pelo usuário.\nExercícios encontrados em wiki.python.org.br",
                    "36 - Desenvolva um programa que faça a tabuada de um número qualquer inteiro que será digitado pelo usuário, mas a tabuada não deve necessariamente iniciar em 1 e terminar em 10, o valor inicial e final devem ser informados também pelo usuário, conforme exemplo abaixo:\n\n    Montar a tabuada de: 5\n    Começar por: 4\n    Terminar em: 7\n\n    Vou montar a tabuada de 5 começando em 4 e terminando em 7:\n    5 X 4 = 20\n    5 X 5 = 25\n    5 X 6 = 30\n    5 X 7 = 35\n\n    Obs: Você deve verificar se o usuário não digitou o final menor que o inicial. \nExercícios encontrados em wiki.python.org.br",
                    "37 - Uma academia deseja fazer um senso entre seus clientes para descobrir o mais alto, o mais baixo, a mais gordo e o mais magro, para isto você deve fazer um programa que pergunte a cada um dos clientes da academia seu código, sua altura e seu peso. O final da digitação de dados deve ser dada quando o usuário digitar 0 (zero) no campo código. Ao encerrar o programa também deve ser informados os códigos e valores do clente mais alto, do mais baixo, do mais gordo e do mais magro, além da média das alturas e dos pesos dos clientes\nExercícios encontrados em wiki.python.org.br",
                    "38 - Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:\n\n    Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;\n    Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;\n    A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário. \nExercícios encontrados em wiki.python.org.br",
                    "39 - Faça um programa que leia dez conjuntos de dois valores, o primeiro representando o número do aluno e o segundo representando a sua altura em centímetros. Encontre o aluno mais alto e o mais baixo. Mostre o número do aluno mais alto e o número do aluno mais baixo, junto com suas alturas.\nExercícios encontrados em wiki.python.org.br",
                    "40 - Foi feita uma estatística em cinco cidades brasileiras para coletar dados sobre acidentes de trânsito. Foram obtidos os seguintes dados:\n\n    Código da cidade;\n    Número de veículos de passeio (em 1999);\n    Número de acidentes de trânsito com vítimas (em 1999). Deseja-se saber:\n    Qual o maior e menor índice de acidentes de transito e a que cidade pertence;\n    Qual a média de veículos nas cinco cidades juntas;\n    Qual a média de acidentes de trânsito nas cidades com menos de 2.000 veículos de passeio. \nExercícios encontrados em wiki.python.org.br",
                    "41 - Faça um programa que receba o valor de uma dívida e mostre uma tabela com os seguintes dados: valor da dívida, valor dos juros, quantidade de parcelas e valor da parcela.\n\n    Os juros e a quantidade de parcelas seguem a tabela abaixo:\n\n    Quantidade de Parcelas  % de Juros sobre o valor inicial da dívida\n    1       0\n    3       10\n    6       15\n    9       20\n    12      25\n\n    Exemplo de saída do programa:\n\n    Valor da Dívida Valor dos Juros Quantidade de Parcelas  Valor da Parcela\n    R$ 1.000,00     0               1                       R$  1.000,00\n    R$ 1.100,00     100             3                       R$    366,00\n    R$ 1.150,00     150             6                       R$    191,67\nExercícios encontrados em wiki.python.org.br",
                    "42 - Faça um programa que leia uma quantidade indeterminada de números positivos e conte quantos deles estão nos seguintes intervalos: [0-25], [26-50], [51-75] e [76-100]. A entrada de dados deverá terminar quando for lido um número negativo.\nExercícios encontrados em wiki.python.org.br",
                    "43 - O cardápio de uma lanchonete é o seguinte:\n\n    Especificação   Código  Preço\n    Cachorro Quente 100     R$ 1,20\n    Bauru Simples   101     R$ 1,30\n    Bauru com ovo   102     R$ 1,50\n    Hambúrguer      103     R$ 1,20\n    Cheeseburguer   104     R$ 1,30\n    Refrigerante    105     R$ 1,00\n\n    Faça um programa que leia o código dos itens pedidos e as quantidades desejadas. Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado. \nExercícios encontrados em wiki.python.org.br",
                    "44 - Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código. Os códigos utilizados são:\n\n    1 , 2, 3, 4  - Votos para os respectivos candidatos \n    (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)\n    5 - Voto Nulo\n    6 - Voto em Branco\n\n    Faça um programa que calcule e mostre:\n    O total de votos para cada candidato;\n    O total de votos nulos;\n    O total de votos em branco;\n    A percentagem de votos nulos sobre o total de votos;\n    A percentagem de votos em branco sobre o total de votos. Para finalizar o conjunto de votos tem-se o valor zero. \nExercícios encontrados em wiki.python.org.br",
                    "45 - Desenvolver um programa para verificar a nota do aluno em uma prova com 10 questões, o programa deve perguntar ao aluno a resposta de cada questão e ao final comparar com o gabarito da prova e assim calcular o total de acertos e a nota (atribuir 1 ponto por resposta certa). Após cada aluno utilizar o sistema deve ser feita uma pergunta se outro aluno vai utilizar o sistema. Após todos os alunos terem respondido informar:\n\n    Maior e Menor Acerto;\n    Total de Alunos que utilizaram o sistema;\n    A Média das Notas da Turma.\n\n    Gabarito da Prova:\n\n    01 - A\n    02 - B\n    03 - C\n    04 - D\n    05 - E\n    06 - E\n    07 - D\n    08 - C\n    09 - B\n    10 - A\n\n    Após concluir isto você poderia incrementar o programa permitindo que o professor digite o gabarito da prova antes dos alunos usarem o programa. \nExercícios encontrados em wiki.python.org.br",
                    "46 - Em uma competição de salto em distância cada atleta tem direito a cinco saltos. No final da série de saltos de cada atleta, o melhor e o pior resultados são eliminados. O seu resultado fica sendo a média dos três valores restantes. Você deve fazer um programa que receba o nome e as cinco distâncias alcançadas pelo atleta em seus saltos e depois informe a média dos saltos conforme a descrição acima informada (retirar o melhor e o pior salto e depois calcular a média). Faça uso de uma lista para armazenar os saltos. Os saltos são informados na ordem da execução, portanto não são ordenados. O programa deve ser encerrado quando não for informado o nome do atleta. A saída do programa deve ser conforme o exemplo abaixo:\n\nAtleta: Rodrigo Curvêllo\n\nPrimeiro Salto: 6.5 m\nSegundo Salto: 6.1 m\nTerceiro Salto: 6.2 m\nQuarto Salto: 5.4 m\nQuinto Salto: 5.3 m\n\nMelhor salto:  6.5 m\nPior salto: 5.3 m\nMédia dos demais saltos: 5.9 m\n\nResultado final:\n\nRodrigo Curvêllo: 5.9 m\nExercícios encontrados em wiki.python.org.br",
                    "47 - Em uma competição de ginástica, cada atleta recebe votos de sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica sendo a média dos votos restantes. Você deve fazer um programa que receba o nome do ginasta e as notas dos sete jurados alcançadas pelo atleta em sua apresentação e depois informe a sua média, conforme a descrição acima informada (retirar o melhor e o pior salto e depois calcular a média com as notas restantes). As notas não são informados ordenadas. Um exemplo de saída do programa deve ser conforme o exemplo abaixo:\n\nAtleta: Aparecido Parente\nNota: 9.9\nNota: 7.5\nNota: 9.5\nNota: 8.5\nNota: 9.0\nNota: 8.5\nNota: 9.7\n\nResultado final:\nAtleta: Aparecido Parente\nMelhor nota: 9.9\nPior nota: 7.5\nMédia: 9,04\nExercícios encontrados em wiki.python.org.br",
                    "48 - Faça um programa que peça um numero inteiro positivo e em seguida mostre este numero invertido.\n\n    Exemplo:\n\n      12376489\n\n      => 98467321\nExercícios encontrados em wiki.python.org.br",
                    "49 - Faça um programa que mostre os n termos da Série a seguir:\n\n      S = 1/1 + 2/3 + 3/5 + 4/7 + 5/9 + ... + n/m. \n\n    Imprima no final a soma da série. \nExercícios encontrados em wiki.python.org.br",
                    "50 - Sendo H= 1 + 1/2 + 1/3 + 1/4 + ... + 1/N, Faça um programa que calcule o valor de H com N termos.\nExercícios encontrados em wiki.python.org.br",
                    "51 - Faça um programa que mostre os n termos da Série a seguir:\n\n      S = 1/1 + 2/3 + 3/5 + 4/7 + 5/9 + ... + n/m. \n\n    Imprima no final a soma da série. \nExercícios encontrados em wiki.python.org.br"
            )),
            new Exercisies("04_ExerciciosListas", Arrays.asList(
                    "01 - Faça um Programa que leia um vetor de 5 números inteiros e mostre-os.\nExercícios encontrados em wiki.python.org.br",
                    "02 - Faça um Programa que leia um vetor de 10 números reais e mostre-os na ordem inversa.\nExercícios encontrados em wiki.python.org.br",
                    "03 - Faça um Programa que leia 4 notas, mostre as notas e a média na tela.\nExercícios encontrados em wiki.python.org.br",
                    "04 - Faça um Programa que leia um vetor de 10 caracteres, e diga quantas consoantes foram lidas. Imprima as consoantes.\nExercícios encontrados em wiki.python.org.br",
                    "05 - Faça um Programa que leia 20 números inteiros e armazene-os num vetor. Armazene os números pares no vetor PAR e os números IMPARES no vetor impar. Imprima os três vetores.\nExercícios encontrados em wiki.python.org.br",
                    "06 - Faça um Programa que peça as quatro notas de 10 alunos, calcule e armazene num vetor a média de cada aluno, imprima o número de alunos com média maior ou igual a 7.0.\nExercícios encontrados em wiki.python.org.br",
                    "07 - Faça um Programa que leia um vetor de 5 números inteiros, mostre a soma, a multiplicação e os números.\nExercícios encontrados em wiki.python.org.br",
                    "08 - Faça um Programa que peça a idade e a altura de 5 pessoas, armazene cada informação no seu respectivo vetor. Imprima a idade e a altura na ordem inversa a ordem lida.\nExercícios encontrados em wiki.python.org.br",
                    "09 - Faça um Programa que leia um vetor A com 10 números inteiros, calcule e mostre a soma dos quadrados dos elementos do vetor.\nExercícios encontrados em wiki.python.org.br",
                    "10 - Faça um Programa que leia dois vetores com 10 elementos cada. Gere um terceiro vetor de 20 elementos, cujos valores deverão ser compostos pelos elementos intercalados dos dois outros vetores.\nExercícios encontrados em wiki.python.org.br",
                    "11 - Altere o programa anterior, intercalando 3 vetores de 10 elementos cada.\nExercícios encontrados em wiki.python.org.br",
                    "12 - Foram anotadas as idades e alturas de 30 alunos. Faça um Programa que determine quantos alunos com mais de 13 anos possuem altura inferior à média de altura desses alunos.\nExercícios encontrados em wiki.python.org.br",
                    "13 - Faça um programa que receba a temperatura média de cada mês do ano e armazene-as em uma lista. Após isto, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram (mostrar o mês por extenso: 1 – Janeiro, 2 – Fevereiro, . . . ). \nExercícios encontrados em wiki.python.org.br",
                    "14 - Utilizando listas faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:\n\n    \"Telefonou para a vítima?\"\n    \"Esteve no local do crime?\"\n    \"Mora perto da vítima?\"\n    \"Devia para a vítima?\"\n    \"Já trabalhou com a vítima?\" O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como \"Suspeita\", entre 3 e 4 como \"Cúmplice\" e 5 como \"Assassino\". Caso contrário, ele será classificado como \"Inocente\". \nExercícios encontrados em wiki.python.org.br",
                    "15 - Faça um programa que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:\n\n    Mostre a quantidade de valores que foram lidos;\n    Exiba todos os valores na ordem em que foram informados, um ao lado do outro;\n    Exiba todos os valores na ordem inversa à que foram informados, um abaixo do outro;\n    Calcule e mostre a soma dos valores;\n    Calcule e mostre a média dos valores;\n    Calcule e mostre a quantidade de valores acima da média calculada;\n    Calcule e mostre a quantidade de valores abaixo de sete;\n    Encerre o programa com uma mensagem; \nExercícios encontrados em wiki.python.org.br",
                    "16 - Utilize uma lista para resolver o problema a seguir. Uma empresa paga seus vendedores com base em comissões. O vendedor recebe $200 por semana mais 9 por cento de suas vendas brutas daquela semana. Por exemplo, um vendedor que teve vendas brutas de $3000 em uma semana recebe $200 mais 9 por cento de $3000, ou seja, um total de $470. Escreva um programa (usando um array de contadores) que determine quantos vendedores receberam salários nos seguintes intervalos de valores:\n\n    $200 - $299\n    $300 - $399\n    $400 - $499\n    $500 - $599\n    $600 - $699\n    $700 - $799\n    $800 - $899\n    $900 - $999\n    $1000 em diante \n\nDesafio: Crie ma fórmula para chegar na posição da lista a partir do salário, sem fazer vários ifs aninhados.\nExercícios encontrados em wiki.python.org.br",
                    "17 - Em uma competição de salto em distância cada atleta tem direito a cinco saltos. O resultado do atleta será determinado pela média dos cinco valores restantes. Você deve fazer um programa que receba o nome e as cinco distâncias alcançadas pelo atleta em seus saltos e depois informe o nome, os saltos e a média dos saltos. O programa deve ser encerrado quando não for informado o nome do atleta. A saída do programa deve ser conforme o exemplo abaixo:\n\nAtleta: Rodrigo Curvêllo\n \nPrimeiro Salto: 6.5 m\nSegundo Salto: 6.1 m\nTerceiro Salto: 6.2 m\nQuarto Salto: 5.4 m\nQuinto Salto: 5.3 m\n\nResultado final:\nAtleta: Rodrigo Curvêllo\nSaltos: 6.5 - 6.1 - 6.2 - 5.4 - 5.3\nMédia dos saltos: 5.9 m\nExercícios encontrados em wiki.python.org.br",
                    "18 - Uma grande emissora de televisão quer fazer uma enquete entre os seus telespectadores para saber qual o melhor jogador após cada jogo. Para isto, faz-se necessário o desenvolvimento de um programa, que será utilizado pelas telefonistas, para a computação dos votos. Sua equipe foi contratada para desenvolver este programa, utilizando a linguagem de programação C++. Para computar cada voto, a telefonista digitará um número, entre 1 e 23, correspondente ao número da camisa do jogador. Um número de jogador igual zero, indica que a votação foi encerrada. Se um número inválido for digitado, o programa deve ignorá-lo, mostrando uma breve mensagem de aviso, e voltando a pedir outro número. Após o final da votação, o programa deverá exibir:\n\n    O total de votos computados;\n    Os númeos e respectivos votos de todos os jogadores que receberam votos;\n    O percentual de votos de cada um destes jogadores;\n    O número do jogador escolhido como o melhor jogador da partida, juntamente com o número de votos e o percentual de votos dados a ele.\n        Observe que os votos inválidos e o zero final não devem ser computados como votos. O resultado aparece ordenado pelo número do jogador. O programa deve fazer uso de arrays. O programa deverá executar o cálculo do percentual de cada jogador através de uma função. Esta função receberá dois parâmetros: o número de votos de um jogador e o total de votos. A função calculará o percentual e retornará o valor calculado. Abaixo segue uma tela de exemplo. O disposição das informações deve ser o mais próxima possível ao exemplo. Os dados são fictícios e podem mudar a cada execução do programa. Ao final, o programa deve ainda gravar os dados referentes ao resultado da votação em um arquivo texto no disco, obedecendo a mesma disposição apresentada na tela. \nEnquete: Quem foi o melhor jogador?\nNúmero do jogador (0=fim): 9Número do jogador (0=fim): 10Número do jogador (0=fim): 9Número do jogador (0=fim): 10Número do jogador (0=fim): 11Número do jogador (0=fim): 10Número do jogador (0=fim): 50Informe um valor entre 1 e 23 ou 0 para sair!Número do jogador (0=fim): 9Número do jogador (0=fim): 9Número do jogador (0=fim): 0\nResultado da votação:\nForam computados 8 votos.\nJogador Votos           %9               4               50,0%10              3               37,5%11              1               12,5%O melhor jogador foi o número 9, com 4 votos, correspondendo a 50% do total de votos.\nExercícios encontrados em wiki.python.org.br",
                    "19 - Uma empresa de pesquisas precisa tabular os resultados da seguinte enquete feita a um grande quantidade de organizações:\n\"Qual o melhor Sistema Operacional para uso em servidores?\"\nAs possíveis respostas são:\n1- Windows Server2- Unix3- Linux4- Netware5- Mac OS6- Outro\n\nVocê foi contratado para desenvolver um programa que leia o resultado da enquete e informe ao final o resultado da mesma. O programa deverá ler os valores até ser informado o valor 0, que encerra a entrada dos dados. Não deverão ser aceitos valores além dos válidos para o programa (0 a 6). Os valores referentes a cada uma das opções devem ser armazenados num vetor. Após os dados terem sido completamente informados, o programa deverá calcular a percentual de cada um dos concorrentes e informar o vencedor da enquete. O formato da saída foi dado pela empresa, e é o seguinte:\n\nSistema Operacional     Votos   %\n-------------------     -----   ---\nWindows Server           1500   17%\nUnix                     3500   40%\nLinux                    3000   34%\nNetware                   500    5%\nMac OS                    150    2%\nOutro                     150    2%\n-------------------     -----\nTotal                    8800\n\nO Sistema Operacional mais votado foi o Unix, com 3500 votos, correspondendo a 40% dos votos.\nExercícios encontrados em wiki.python.org.br",
                    "20 - As Organizações Tabajara resolveram dar um abono aos seus colaboradores em reconhecimento ao bom resultado alcançado durante o ano que passou. Para isto contratou você para desenvolver a aplicação que servirá como uma projeção de quanto será gasto com o pagamento deste abono.\n\n    Após reuniões envolvendo a diretoria executiva, a diretoria financeira e os representantes do sindicato laboral, chegou-se a seguinte forma de cálculo: \n\n    a.Cada funcionário receberá o equivalente a 20% do seu salário bruto de dezembro; a.O piso do abono será de 100 reais, isto é, aqueles funcionários cujo salário for muito baixo, recebem este valor mínimo; Neste momento, não se deve ter nenhuma preocupação com colaboradores com tempo menor de casa, descontos, impostos ou outras particularidades. Seu programa deverá permitir a digitação do salário de um número indefinido (desconhecido) de salários. Um valor de salário igual a 0 (zero) encerra a digitação. Após a entrada de todos os dados o programa deverá calcular o valor do abono concedido a cada colaborador, de acordo com a regra definida acima. Ao final, o programa deverá apresentar:\n    O salário de cada funcionário, juntamente com o valor do abono;\n    O número total de funcionário processados;\n    O valor total a ser gasto com o pagamento do abono;\n    O número de funcionário que receberá o valor mínimo de 100 reais;\n    O maior valor pago como abono; A tela abaixo é um exemplo de execução do programa, apenas para fins ilustrativos. Os valores podem mudar a cada execução do programa. \n\nProjeção de Gastos com Abono\n============================ \n\nSalário: 1000\nSalário: 300\nSalário: 500\nSalário: 100\nSalário: 4500\nSalário: 0\n\nSalário    - Abono     \nR$ 1000.00 - R$  200.00\nR$  300.00 - R$  100.00\nR$  500.00 - R$  100.00\nR$  100.00 - R$  100.00\nR$ 4500.00 - R$  900.00\n\nForam processados 5 colaboradores\nTotal gasto com abonos: R$ 1400.00\nValor mínimo pago a 3 colaboradores\nMaior valor de abono pago: R$ 900.00\n\nExercícios encontrados em wiki.python.org.br",
                    "21 - Faça um programa que carregue uma lista com os modelos de cinco carros (exemplo de modelos: FUSCA, GOL, VECTRA etc). Carregue uma outra lista com o consumo desses carros, isto é, quantos quilômetros cada um desses carros faz com um litro de combustível. Calcule e mostre:\n\n    O modelo do carro mais econômico;\n    Quantos litros de combustível cada um dos carros cadastrados consome para percorrer uma distância de 1000 quilômetros e quanto isto custará, considerando um que a gasolina custe R$ 2,25 o litro. Abaixo segue uma tela de exemplo. O disposição das informações deve ser o mais próxima possível ao exemplo. Os dados são fictícios e podem mudar a cada execução do programa. \n\nComparativo de Consumo de Combustível\n\nVeículo 1\nNome: fusca\nKm por litro: 7\nVeículo 2\nNome: gol\nKm por litro: 10\nVeículo 3\nNome: uno\nKm por litro: 12.5\nVeículo 4\nNome: Vectra\nKm por litro: 9\nVeículo 5\nNome: Peugeout\nKm por litro: 14.5\n\nRelatório Final\n 1 - fusca           -    7.0 -  142.9 litros - R$ 321.43\n 2 - gol             -   10.0 -  100.0 litros - R$ 225.00\n 3 - uno             -   12.5 -   80.0 litros - R$ 180.00\n 4 - vectra          -    9.0 -  111.1 litros - R$ 250.00\n 5 - peugeout        -   14.5 -   69.0 litros - R$ 155.17\nO menor consumo é do peugeout.\nExercícios encontrados em wiki.python.org.br",
                    "22 - Sua organização acaba de contratar um estagiário para trabalhar no Suporte de Informática, com a intenção de fazer um levantamento nas sucatas encontradas nesta área. A primeira tarefa dele é testar todos os cerca de 200 mouses que se encontram lá, testando e anotando o estado de cada um deles, para verificar o que se pode aproveitar deles.\n\n    Foi requisitado que você desenvolva um programa para registrar este levantamento. O programa deverá receber um número indeterminado de entradas, cada uma contendo: um número de identificação do mouse o tipo de defeito:\n    necessita da esfera;\n    necessita de limpeza; a.necessita troca do cabo ou conector; a.quebrado ou inutilizado Uma identificação igual a zero encerra o programa. Ao final o programa deverá emitir o seguinte relatório: \n\nQuantidade de mouses: 100\n\nSituação                        Quantidade              Percentual\n1- necessita da esfera                  40                     40%\n2- necessita de limpeza                 30                     30%\n3- necessita troca do cabo ou conector  15                     15%\n4- quebrado ou inutilizado              15                     15%\nExercícios encontrados em wiki.python.org.br",
                    "23 - A ACME Inc., uma empresa de 500 funcionários, está tendo problemas de espaço em disco no seu servidor de arquivos. Para tentar resolver este problema, o Administrador de Rede precisa saber qual o espaço ocupado pelos usuários, e identificar os usuários com maior espaço ocupado. Através de um programa, baixado da Internet, ele conseguiu gerar o seguinte arquivo, chamado \"usuarios.txt\":\n\nalexandre       456123789\nanderson        1245698456\nantonio         123456456\ncarlos          91257581\ncesar           987458\nrosemary        789456125\n\nNeste arquivo, o nome do usuário possui 15 caracteres. A partir deste arquivo, você deve criar um programa que gere um relatório, chamado \"relatório.txt\", no seguinte formato:\n\nACME Inc.               Uso do espaço em disco pelos usuários\n------------------------------------------------------------------------\nNr.  Usuário        Espaço utilizado     % do uso\n\n1    alexandre       434,99 MB             16,85%\n2    anderson       1187,99 MB             46,02%\n3    antonio         117,73 MB              4,56%\n4    carlos           87,03 MB              3,37%\n5    cesar             0,94 MB              0,04%\n6    rosemary        752,88 MB             29,16%\n\nEspaço total ocupado: 2581,57 MB\nEspaço médio ocupado: 430,26 MB\n\nO arquivo de entrada deve ser lido uma única vez, e os dados armazenados em memória, caso sejam necessários, de forma a agilizar a execução do programa. A conversão da espaço ocupado em disco, de bytes para megabytes deverá ser feita através de uma função separada, que será chamada pelo programa principal. O cálculo do percentual de uso também deverá ser feito através de uma função, que será chamada pelo programa principal. \nExercícios encontrados em wiki.python.org.br",
                    "24 - Faça um programa que simule um lançamento de dados. Lance o dado 100 vezes e armazene os resultados em um vetor . Depois, mostre quantas vezes cada valor foi conseguido. Dica: use um vetor de contadores(1-6) e uma função para gerar numeros aleatórios, simulando os lançamentos dos dados. \nExercícios encontrados em wiki.python.org.br"
            )),
            new Exercisies("05_ExerciciosFuncoes", Arrays.asList(
                    "1 - Faça um programa para imprimir:\n\n        1\n        2   2\n        3   3   3\n        .....\n        n   n   n   n   n   n  ... n\n\n    para um n informado pelo usuário. Use uma função que receba um valor n inteiro e imprima até a n-ésima linha. ",
                    "2 - Faça um programa para imprimir:\n\n        1\n        1   2\n        1   2   3\n        .....\n        1   2   3   ...  n\n\n    para um n informado pelo usuário. Use uma função que receba um valor n inteiro imprima até a n-ésima linha. ",
                    "3 - Faça um programa, com uma função que necessite de três argumentos, e que forneça a soma desses três argumentos.",
                    "4 - Faça um programa, com uma função que necessite de um argumento. A função retorna o valor de caractere \"P\", se seu argumento for positivo, e \"N\", se seu argumento for zero ou negativo.",
                    "5 - Faça um programa com uma função chamada somaImposto. A função possui dois parâmetros formais: taxaImposto, que é a quantia de imposto sobre vendas expressa em porcentagem e custo, que é o custo de um item antes do imposto. A função “altera” o valor de custo para incluir o imposto sobre vendas.",
                    "6 - Faça um programa que converta da notação de 24 horas para a notação de 12 horas. Por exemplo, o programa deve converter 14:25 em 2:25 P.M. A entrada é dada em dois inteiros. Deve haver pelo menos duas funções: uma para fazer a conversão e uma para a saída. Registre a informação A.M./P.M. como um valor ‘A’ para A.M. e ‘P’ para P.M. Assim, a função para efetuar as conversões terá um parâmetro formal para registrar se é A.M. ou P.M. Inclua um loop que permita que o usuário repita esse cálculo para novos valores de entrada todas as vezes que desejar.",
                    "7 - Faça um programa que use a função valorPagamento para determinar o valor a ser pago por uma prestação de uma conta. O programa deverá solicitar ao usuário o valor da prestação e o número de dias em atraso e passar estes valores para a função valorPagamento, que calculará o valor a ser pago e devolverá este valor ao programa que a chamou. O programa deverá então exibir o valor a ser pago na tela. Após a execução o programa deverá voltar a pedir outro valor de prestação e assim continuar até que seja informado um valor igual a zero para a prestação. Neste momento o programa deverá ser encerrado, exibindo o relatório do dia, que conterá a quantidade e o valor total de prestações pagas no dia. O cálculo do valor a ser pago é feito da seguinte forma. Para pagamentos sem atraso, cobrar o valor da prestação. Quando houver atraso, cobrar 3% de multa, mais 0,1% de juros por dia de atraso.",
                    "8 - Faça uma função que informe a quantidade de dígitos de um determinado número inteiro informado.",
                    "9 - Reverso do número. Faça uma função que retorne o reverso de um número inteiro informado. Por exemplo: 127 -> 721.",
                    "10 - Jogo de Craps. Faça um programa de implemente um jogo de Craps. O jogador lança um par de dados, obtendo um valor entre 2 e 12. Se, na primeira jogada, você tirar 7 ou 11, você um \"natural\" e ganhou. Se você tirar 2, 3 ou 12 na primeira jogada, isto é chamado de \"craps\" e você perdeu. Se, na primeira jogada, você fez um 4, 5, 6, 8, 9 ou 10,este é seu \"Ponto\". Seu objetivo agora é continuar jogando os dados até tirar este número novamente. Você perde, no entanto, se tirar um 7 antes de tirar este Ponto novamente.",
                    "11 - Data com mês por extenso. Construa uma função que receba uma data no formato DD/MM/AAAA e devolva uma string no formato D de mesPorExtenso de AAAA. Opcionalmente, valide a data e retorne NULL caso a data seja inválida.",
                    "12 - Embaralha palavra. Construa uma função que receba uma string como parâmetro e devolva outra string com os carateres embaralhados. Por exemplo: se função receber a palavra python, pode retornar npthyo, ophtyn ou qualquer outra combinação possível, de forma aleatória. Padronize em sua função que todos os caracteres serão devolvidos em caixa alta ou caixa baixa, independentemente de como foram digitados.",
                    "13 - Desenha moldura. Construa uma função que desenhe um retângulo usando os caracteres \"+\" , \"−\" e \"|\". Esta função deve receber dois parâmetros, linhas e colunas, sendo que o valor por omissão é o valor mínimo igual a 1 e o valor máximo é 20. Se valores fora da faixa forem informados, eles devem ser modificados para valores dentro da faixa de forma elegante.",
                    "14 - Quadrado mágico. Um quadrado mágico é aquele dividido em linhas e colunas, com um número em cada posição e no qual a soma das linhas, colunas e diagonais é a mesma. Por exemplo, veja um quadrado mágico de lado 3, com números de 1 a 9:\n\n    8  3  4 \n    1  5  9\n    6  7  2\n\n    Elabore uma função que identifica e mostra na tela todos os quadrados mágicos com as características acima. Dica: produza todas as combinações possíveis e verifique a soma quando completar cada quadrado. Usar um vetor de 1 a 9 parece ser mais simples que usar uma matriz 3x3. "
            )),
            new Exercisies("06_ExerciciosComStrings", Arrays.asList(
                    "1 - Tamanho de strings. Faça um programa que leia 2 strings e informe o conteúdo delas seguido do seu comprimento. Informe também se as duas strings possuem o mesmo comprimento e são iguais ou diferentes no conteúdo.\n\n    Compara duas strings\n    String 1: Brasil Hexa 2006\n    String 2: Brasil! Hexa 2006!\n    Tamanho de \"Brasil Hexa 2006\": 16 caracteres\n    Tamanho de \"Brasil! Hexa 2006!\": 18 caracteres\n    As duas strings são de tamanhos diferentes.\n    As duas strings possuem conteúdo diferente.",
                    "2 - Nome ao contrário em maiúsculas. Faça um programa que permita ao usuário digitar o seu nome e em seguida mostre o nome do usuário de trás para frente utilizando somente letras maiúsculas. Dica: lembre−se que ao informar o nome o usuário pode digitar letras maiúsculas ou minúsculas.",
                    "3 - Nome na vertical. Faça um programa que solicite o nome do usuário e imprima-o na vertical.\n\n    F\n    U\n    L\n    A\n    N\n    O",
                    "4 - Nome na vertical em escada. Modifique o programa anterior de forma a mostrar o nome em formato de escada.\n\n    F\n    FU\n    FUL\n    FULA\n    FULAN\n    FULANO",
                    "5 - Nome na vertical em escada invertida. Altere o programa anterior de modo que a escada seja invertida.\n\n    FULANO\n    FULAN\n    FULA\n    FUL\n    FU\n    F",
                    "6 - Data por extenso. Faça um programa que solicite a data de nascimento (dd/mm/aaaa) do usuário e imprima a data com o nome do mês por extenso.\n\n    Data de Nascimento: 29/10/1973\n    Você nasceu em  29 de Outubro de 1973.",
                    "7 - Conta espaços e vogais. Dado uma string com uma frase informada pelo usuário (incluindo espaços em branco), conte:\n\n    quantos espaços em branco existem na frase.\n    quantas vezes aparecem as vogais a, e, i, o, u. ",
                    "8 - Palíndromo. Um palíndromo é uma seqüência de caracteres cuja leitura é idêntica se feita da direita para esquerda ou vice−versa. Por exemplo: OSSO e OVO são palíndromos. Em textos mais complexos os espaços e pontuação são ignorados. A frase SUBI NO ONIBUS é o exemplo de uma frase palíndroma onde os espaços foram ignorados. Faça um programa que leia uma seqüência de caracteres, mostre−a e diga se é um palíndromo ou não.",
                    "9 - Verificação de CPF. Desenvolva um programa que solicite a digitação de um número de CPF no formato xxx.xxx.xxx-xx e indique se é um número válido ou inválido através da validação dos dígitos verificadores edos caracteres de formatação.",
                    "10 - Número por extenso. Escreva um programa que solicite ao usuário a digitação de um número até 99 e imprima-o na tela por extenso.",
                    "11 - Jogo de Forca. Desenvolva um jogo da forca. O programa terá uma lista de palavras lidas de um arquivo texto e escolherá uma aleatoriamente. O jogador poderá errar 6 vezes antes de ser enforcado.\n\n    Digite uma letra: A\n    -> Você errou pela 1ª vez. Tente de novo!\n\n    Digite uma letra: O\n    A palavra é: _ _ _ _ O\n\n    Digite uma letra: E\n    A palavra é: _ E _ _ O\n\n    Digite uma letra: S\n    -> Você errou pela 2ª vez. Tente de novo!",
                    "12 - Valida e corrige número de telefone. Faça um programa que leia um número de telefone, e corrija o número no caso deste conter somente 7 dígitos, acrescentando o '3' na frente. O usuário pode informar o número com ou sem o traço separador.\n\n    Valida e corrige número de telefone\n    Telefone: 461-0133\n    Telefone possui 7 dígitos. Vou acrescentar o digito três na frente.\n    Telefone corrigido sem formatação: 34610133\n    Telefone corrigido com formatação: 3461-0133",
                    "13 - Jogo da palavra embaralhada. Desenvolva um jogo em que o usuário tenha que adivinhar uma palavra que será mostrada com as letras embaralhadas. O programa terá uma lista de palavras lidas de um arquivo texto e escolherá uma aleatoriamente. O jogador terá seis tentativas para adivinhar a palavra. Ao final a palavra deve ser mostrada na tela, informando se o usuário ganhou ou perdeu o jogo.",
                    "14 - Leet spek generator. Leet é uma forma de se escrever o alfabeto latino usando outros símbolos em lugar das letras, como números por exemplo. A própria palavra leet admite muitas variações, como l33t ou 1337. O uso do leet reflete uma subcultura relacionada ao mundo dos jogos de computador e internet, sendo muito usada para confundir os iniciantes e afirmar-se como parte de um grupo. Pesquise sobre as principais formas de traduzir as letras. Depois, faça um programa que peça uma texto e transforme-o para a grafia leet speak. "
            )),
            new Exercisies("07_ExerciciosArquivos", Arrays.asList(
                    "1 - Faça um programa que leia um arquivo texto contendo uma lista de endereços IP e gere um outro arquivo, contendo um relatório dos endereços IP válidos e inválidos.\n\n    O arquivo de entrada possui o seguinte formato: \n\n200.135.80.9\n192.168.1.1\n8.35.67.74\n257.32.4.5\n85.345.1.2\n1.2.3.4\n9.8.234.5\n192.168.0.256\n\n    O arquivo de saída possui o seguinte formato: \n\n[Endereços válidos:]\n200.135.80.9\n192.168.1.1\n8.35.67.74\n1.2.3.4\n\n[Endereços inválidos:]\n257.32.4.5\n85.345.1.2\n9.8.234.5\n192.168.0.256",
                    "2 - A ACME Inc., uma empresa de 500 funcionários, está tendo problemas de espaço em disco no seu servidor de arquivos. Para tentar resolver este problema, o Administrador de Rede precisa saber qual o espaço ocupado pelos usuários, e identificar os usuários com maior espaço ocupado. Através de um programa, baixado da Internet, ele conseguiu gerar o seguinte arquivo, chamado \"usuarios.txt\":\n\nalexandre       456123789\nanderson        1245698456\nantonio         123456456\ncarlos          91257581\ncesar           987458\nrosemary        789456125\n\nNeste arquivo, o nome do usuário possui 15 caracteres. A partir deste arquivo, você deve criar um programa que gere um relatório, chamado \"relatório.txt\", no seguinte formato:\n\nACME Inc.               Uso do espaço em disco pelos usuários\n------------------------------------------------------------------------\nNr.  Usuário        Espaço utilizado     % do uso\n\n1    alexandre       434,99 MB             16,85%\n2    anderson       1187,99 MB             46,02%\n3    antonio         117,73 MB              4,56%\n4    carlos           87,03 MB              3,37%\n5    cesar             0,94 MB              0,04%\n6    rosemary        752,88 MB             29,16%\n\nEspaço total ocupado: 2581,57 MB\nEspaço médio ocupado: 430,26 MB\n\nO arquivo de entrada deve ser lido uma única vez, e os dados armazenados em memória, caso sejam necessários, de forma a agilizar a execução do programa. A conversão da espaço ocupado em disco, de bytes para megabytes deverá ser feita através de uma função separada, que será chamada pelo programa principal. O cálculo do percentual de uso também deverá ser feito através de uma função, que será chamada pelo programa principal."
            )),
            new Exercisies("08_ExerciciosClasses", Arrays.asList(
                    "1 - Classe Bola: Crie uma classe que modele uma bola:\n\n    a - Atributos: Cor, circunferência, material\n    b - Métodos: trocaCor e mostraCor ",
                    "2 - Classe Quadrado: Crie uma classe que modele um quadrado:\n\n    a - Atributos: Tamanho do lado\n    b - Métodos: Mudar valor do Lado, Retornar valor do Lado e calcular Área; ",
                    "3 - Classe Retangulo: Crie uma classe que modele um retangulo:\n\n    a - Atributos: LadoA, LadoB (ou Comprimento e Largura, ou Base e Altura, a escolher)\n    b - Métodos: Mudar valor dos lados, Retornar valor dos lados, calcular Área e calcular Perímetro;\n    c - Crie um programa que utilize esta classe. Ele deve pedir ao usuário que informe as medidades de um local. Depois, deve criar um objeto com as medidas e calcular a quantidade de pisos e de rodapés necessárias para o local. ",
                    "4 - Classe Pessoa: Crie uma classe que modele uma pessoa:\n\n    a - Atributos: nome, idade, peso e altura\n    b - Métodos: Envelhercer, engordar, emagrecer, crescer. Obs: Por padrão, a cada ano que nossa pessoa envelhece, sendo a idade dela menor que 21 anos, ela deve crescer 0,5 cm. ",
                    "5 - Classe Conta Corrente: Crie uma classe para implementar uma conta corrente. A classe deve possuir os seguintes atributos: número da conta, nome do correntista e saldo. Os métodos são os seguintes: alterarNome, depósito e saque; No construtor, saldo é opcional, com valor default zero e os demais atributos são obrigatórios.",
                    "6 - Classe TV: Faça um programa que simule um televisor criando-o como um objeto. O usuário deve ser capaz de informar o número do canal e aumentar ou diminuir o volume. Certifique-se de que o número do canal e o nível do volume permanecem dentro de faixas válidas.",
                    "7 - Classe Bichinho Virtual:Crie uma classe que modele um Tamagushi (Bichinho Eletrônico):\n\n    Atributos: Nome, Fome, Saúde e Idade b. Métodos: Alterar Nome, Fome, Saúde e Idade; Retornar Nome, Fome, Saúde e Idade Obs: Existe mais uma informação que devemos levar em consideração, o Humor do nosso tamagushi, este humor é uma combinação entre os atributos Fome e Saúde, ou seja, um campo calculado, então não devemos criar um atributo para armazenar esta informação por que ela pode ser calculada a qualquer momento. ",
                    "8 - Classe Macaco: Desenvolva uma classe Macaco,que possua os atributos nome e bucho (estomago) e pelo menos os métodos comer(), verBucho() e digerir(). Faça um programa ou teste interativamente, criando pelo menos dois macacos, alimentando-os com pelo menos 3 alimentos diferentes e verificando o conteúdo do estomago a cada refeição. Experimente fazer com que um macaco coma o outro. É possível criar um macaco canibal? ",
                    "9 - Classe Ponto e Retangulo: Faça um programa completo utilizando funções e classes que:\n\n    a - Possua uma classe chamada Ponto, com os atributos x e y.\n    b - Possua uma classe chamada Retangulo, com os atributos largura e altura.\n    c - Possua uma função para imprimir os valores da classe Ponto\n    d - Possua uma função para encontrar o centro de um Retângulo.\n    e - Você deve criar alguns objetos da classe Retangulo.\n    f - Cada objeto deve ter um vértice de partida, por exemplo, o vértice inferior esquerdo do retângulo, que deve ser um objeto da classe Ponto.\n    g - A função para encontrar o centro do retângulo deve retornar o valor para um objeto do tipo ponto que indique os valores de x e y para o centro do objeto.\n    h - O valor do centro do objeto deve ser mostrado na tela\n    i - Crie um menu para alterar os valores do retângulo e imprimir o centro deste retângulo. ",
                    "10 - Classe Bomba de Combustível: Faça um programa completo utilizando classes e métodos que:\n\n    a - Possua uma classe chamada bombaCombustível, com no mínimo esses atributos:\n        I - tipoCombustivel.\n        II - valorLitro\n        III - quantidadeCombustivel \n    b - Possua no mínimo esses métodos:\n        I - abastecerPorValor( ) – método onde é informado o valor a ser abastecido e mostra a quantidade de litros que foi colocada no veículo\n        II - abastecerPorLitro( ) – método onde é informado a quantidade em litros de combustível e mostra o valor a ser pago pelo cliente.\n        III - alterarValor( ) – altera o valor do litro do combustível.\n        IV - alterarCombustivel( ) – altera o tipo do combustível.\n        V - alterarQuantidadeCombustivel( ) – altera a quantidade de combustível restante na bomba. \n    OBS: Sempre que acontecer um abastecimento é necessário atualizar a quantidade de combustível total na bomba.",
                    "11 - Classe carro: Implemente uma classe chamada Carro com as seguintes propriedades:\n\n        Um veículo tem um certo consumo de combustível (medidos em km / litro) e uma certa quantidade de combustível no tanque.\n    a - O consumo é especificado no construtor e o nível de combustível inicial é 0.\n    b - Forneça um método andar( ) que simule o ato de dirigir o veículo por uma certa distância, reduzindo o nível de combustível no tanque de gasolina.\n    c - Forneça um método obterGasolina( ), que retorna o nível atual de combustível.\n    d - Forneça um método adicionarGasolina( ), para abastecer o tanque. Exemplo de uso:\n\n    e - meuFusca = Carro(15);           # 15 quilômetros por litro de combustível. \n    meuFusca.adicionarGasolina(20); # abastece com 20 litros de combustível. \n    meuFusca.andar(100);            # anda 100 quilômetros.\n    meuFusca.obterGasolina()        # Imprime o combustível que resta no tanque.",
                    "12 - Classe Conta de Investimento: Faça uma classe contaInvestimento que seja semelhante a classe contaBancaria, com a diferença de que se adicione um atributo taxaJuros. Forneça um construtor que configure tanto o saldo inicial como a taxa de juros. Forneça um método adicioneJuros (sem parâmetro explícito) que adicione juros à conta. Escreva um programa que construa uma poupança com um saldo inicial de R$1000,00 e uma taxa de juros de 10%. Depois aplique o método adicioneJuros() cinco vezes e imprime o saldo resultante.",
                    "13 - Classe Funcionário: Implemente a classe Funcionário. Um empregado tem um nome (um string) e um salário(um double). Escreva um construtor com dois parâmetros (nome e salário) e métodos para devolver nome e salário. Escreva um pequeno programa que teste sua classe.",
                    "14 - Aprimore a classe do exercício anterior para adicionar o método aumentarSalario (porcentualDeAumento) que aumente o salário do funcionário em uma certa porcentagem.\n\n    Exemplo de uso:\n\n      harry=funcionário(\"Harry\",25000)\n      harry.aumentarSalario(10)",
                    "15 - Classe Bichinho Virtual++: Melhore o programa do bichinho virtual, permitindo que o usuário especifique quanto de comida ele fornece ao bichinho e por quanto tempo ele brinca com o bichinho. Faça com que estes valores afetem quão rapidamente os níveis de fome e tédio caem.",
                    "16 - Crie uma \"porta escondida\" no programa do programa do bichinho virtual que mostre os valores exatos dos atributos do objeto. Consiga isto mostrando o objeto quando uma opção secreta, não listada no menu, for informada na escolha do usuário. Dica: acrescente um método especial str() à classe Bichinho.",
                    "17 - Crie uma Fazenda de Bichinhos instanciando vários objetos bichinho e mantendo o controle deles através de uma lista. Imite o funcionamento do programa básico, mas ao invés de exigis que o usuário tome conta de um único bichinho, exija que ele tome conta da fazenda inteira. Cada opção do menu deveria permitir que o usuário executasse uma ação para todos os bichinhos (alimentar todos os bichinhos, brincar com todos os bichinhos, ou ouvir a todos os bichinhos). Para tornar o programa mais interessante, dê para cada bichinho um nivel inicial aleatório de fome e tédio. "
            )),
            new Exercisies("09_ListaDeExerciciosProjetos", Arrays.asList(
                    "1 - Controle de cotas de disco. A ACME Inc., uma organização com mais de 1500 funcionários, está tendo problemas de espaço em disco no seu servidor de arquivos. Para tentar resolver este problema, o Administrador de Rede precisa saber qual o espaço em disco ocupado pelas contas dos usuários, e identificar os usuários com maior espaço ocupado. Através de um aplicativo baixado da Internet, ele conseguiu gerar o seguinte arquivo, chamado usuarios.txt:\n\nalexandre       456123789\nanderson        1245698456\nantonio         123456456\ncarlos          91257581\ncesar           987458\nrosemary        789456125\n\n    Neste arquivo, o primeiro campo corresponde ao login do usuário e o segundo ao espaço em disco ocupado pelo seu diretório home. A partir deste arquivo, você deve criar um programa que gere um relatório, chamado relatório.txt, no seguinte formato: \n\nACME Inc.           Uso do espaço em disco pelos usuários\n------------------------------------------------------------------------\nNr.  Usuário        Espaço utilizado     % do uso\n\n1    alexandre       434,99 MB            16,85%\n2    anderson       1187,99 MB            46,02%\n3    antonio         117,73 MB             4,56%\n4    carlos           87,03 MB             3,37%\n5    cesar             0,94 MB             0,04%\n6    rosemary        752,88 MB            29,16%\n\nEspaço total ocupado: 2581,57 MB\nEspaço médio ocupado: 430,26 MB\n\n    O arquivo de entrada deve ser lido uma única vez, e os dados armazenados em memória, caso sejam necessários, de forma a agilizar a execução do programa. A conversão da espaço ocupado em disco, de bytes para megabytes deverá ser feita através de uma função separada, que será chamada pelo programa principal. O cálculo do percentual de uso também deverá ser feito através de uma função, que será chamada pelo programa principal.\n\n    Recursos adicionais: opcionalmente, desenvolva as seguintes funcionalidades:\n    Ordenar os usuários pelo percentual de espaço ocupado;\n\n    Mostrar apenas os n primeiros em uso, definido pelo usuário;\n    Gerar a saída numa página html;\n    Criar o programa que lê as pastas e gera o arquivo inicial; ",
                    "2 - Analisador de logs do Apache. Desenvolva um analisador de log do Apache que mostre quais as strings de pesquisa do google que mais levam internautas para o site da sua organização.",
                    "3 - Analisador de logs do Squid: sites bloqueados. Desenvolva um analisador de log do Squid que mostre quais os sites mais bloqueados em uma organização. "
            ))
    );

    public void makeNow(String language) throws IOException {
        for (Exercisies element: this.exercisiesListBr) {
            MakeFile makeFile = new MakeFile();
            makeFile.makeFolders(language, element.getName(), element.getExercisies());
        }
        File file = new File("./dev/"+language.toLowerCase());
        if(! file.exists()) {
            System.out.println("Language not found or not implemented");
        }
    }
}
